<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.vitalx</groupId>
    <artifactId>api-zoo</artifactId>
    <description>API using Spring for visualize a Zoo</description>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>api-zoo-domain</module>
        <module>api-zoo-application</module>
        <module>api-zoo-infrastructure</module>
        <module>api-zoo-exposition</module>
    </modules>

    <properties>
        <!-- Define dependence versions -->
        <java.version>21</java.version>
        <spring-boot.version>3.2.0</spring-boot.version>
        <spring-context.version>6.1.21</spring-context.version>
        <postgres.version>42.7.7</postgres.version>
        <io.springfox.version>3.0.0</io.springfox.version>
        <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <spring-boot-starter-parent.version>${spring-boot.version}</spring-boot-starter-parent.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>${spring-boot.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
            <version>3.4.10</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
